### ISSUE TITLE
Xcode R5Streaming.framework Link Error

### ISSUE THREAD

**Issue by 34tm4n** [red5pro/streaming-ios#47]
Hello

I have integrated R5Streaming.framework in Xcode 8.1 swift project but while build the project i am getting this error

Undefined symbols for architecture armv7:
  "operator new[](unsigned long)", referenced from:
      ___29-[R5AACEncoder processAudio:]_block_invoke in R5Streaming(R5AACEncoder.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks

**Comment by HoldenMills** [comment]
Are you following a specific documentation file?  Or are you trying to build one of our examples hosted on Github?  Please provide me the link to the documentation or example app.
